### ISSUE TITLE
build failed on mac

### ISSUE THREAD

**Issue by 0xtyls** [TraceMachina/turbo-cache#101]
Hi,

I'm trying to build turbo-cache on Mac. Bazel build returns this error message:

error[E0432]: unresolved import `libc`
  --> external/raze__tempfile__3_3_0/src/file/imp/unix.rs:19:5
   |
19 | use libc::{c_char, c_int, link, rename, unlink};
   |     ^^^^ use of undeclared crate or module `libc`

error: aborting due to previous error

**Comment by allada** [comment]
Yes, currently this is only compatible for linux, but only because this project relies on `renameat2` because it offers atomic file swaps/renames. We could introduce some locks if `renameat2` is not available on the system, but I haven't yet got around to it.

**Comment by chrisstaite-menlo** [comment]
This is probably also resolved by #108

**Comment by chrisstaite-menlo** [comment]
Still doesn't work on a Mac that has a case-insensitive file system as proto/build and proto/BUILD both exist.

**Comment by chrisstaite-menlo** [comment]
Even if you fix that, io_lifetimes depends on libc which does exist for macOS.  The io_lifetimes crate is a dep of is-terminal and rustix.

rustix is a dep of tempfile and tempfile is a dep of prost-build.

is-terminal is a dep of anstream and anstream is a dep of clap_builder.

Funnily these are both just build deps, so there's actually nothing stopping the compiled code from running on macOS.

**Comment by allada** [comment]
You can now build with cargo on macs instead, so closing this issue.
