### ISSUE TITLE
Instance name might contain /

### ISSUE THREAD

**Issue by chrisstaite-menlo** [TraceMachina/turbo-cache#269]
When an instance name contains one or more '/' the parsing of URIs is broken as it splits on '/' and has the first value optional instance name or not, but if the instance name contains a '/' then this breaks.

**Comment by allada** [comment]
We can just assert on startup if they use a "/", right?

**Comment by chrisstaite-menlo** [comment]
We could, but it's actually useful for Chromium because it prints a warning every time you compile if you change your instance name from the default and the default is `projects/rbe-chrome-untrusted/instances/default_instance`

**Comment by allada** [comment]
Interesting, I wounder if it is even possible to process slashes in the instance name? That default is probably legacy holdover from old systems at google.

**Comment by chrisstaite-menlo** [comment]
It seems to work just fine except for this one bit of parsing in `ResourceInfo`.  It should be pretty trivial to match against the configured instance names.

**Comment by allada** [comment]
Yeah, I think it just needs to parse the string backwards instead of forward and it should work out.
