### ISSUE TITLE
Sharding store

### ISSUE THREAD

**Issue by chrisstaite-menlo** [TraceMachina/turbo-cache#287]
It would be nice to be able to scale up FilesystemStore over more than one node.  Although we can apply FastSlow local caches (like with workers) and we can do SizePartitioningStore, it would be nice to have some kind of ShardingStore that sends requests to N GrpcStores based on some sharding algorithm.

**Comment by allada** [comment]
Oh yeah, this is extremely simple todo. I'll add it on my backlog.

**Comment by chrisstaite-menlo** [comment]
What needs considering is how you can scale in the future.  Say you were sharding to 3 and you want to add a fourth, how do you re-distribute, or do you just write off the whole store and start from scratch?

**Comment by allada** [comment]
At this point it sounds more like a database and will require a control plane. If a user needs to retain the entire database and add a node, would it be better to just use a proper sharing database (like Redis, Mongo, or another key-value supported database)?

**Comment by chrisstaite-menlo** [comment]
Perhaps that's another kind of store that can be backed by a database to distribute between shards/replicas.  A nice simple model if you don't mind rebuilding or a database backed model if you want to keep your data when scaling up.

**Comment by allada** [comment]
I've been looking into this and it is very straight forward. I see two ways to do this, we can either have how it shards configured behind the scenes or introduce a `PrefixStore`.

The `PrefixStore` would give full control on how sharding is done in the config, but does require a bit more config.
The other option is a `ShardStore`, which hides away the algorithm that is used.

I like the idea of using `ShardStore` for simplicity, but I am concerned someone may come along and want to make changes to the config and have fine-grained control of the routing rules itself.

I can't think of a real scenario where a user would want to use `PrefixStore` over `ShardStore`.

For reference here's the algorithm I have done right now for `ShardStore`:
```rs
fn get_store_index(&self, digest: &DigestInfo) -> usize {
    // Quote from std primitive array documentation:
    //     Array’s try_from(slice) implementations (and the corresponding slice.try_into()
    //     array implementations) succeed if the input slice length is the same as the result
    //     array length. They optimize especially well when the optimizer can easily determine
    //     the slice length, e.g. <[u8; 4]>::try_from(&slice[4..8]).unwrap(). Array implements
    //     TryFrom returning.
    let key: u32 = 0
        .bitxor(u32::from_le_bytes(digest.packed_hash[0..4].try_into().unwrap()))
        .bitxor(u32::from_le_bytes(digest.packed_hash[4..8].try_into().unwrap()))
        .bitxor(u32::from_le_bytes(digest.packed_hash[8..12].try_into().unwrap()))
        .bitxor(u32::from_le_bytes(digest.packed_hash[12..16].try_into().unwrap()))
        .bitxor(u32::from_le_bytes(digest.packed_hash[16..20].try_into().unwrap()))
        .bitxor(u32::from_le_bytes(digest.packed_hash[20..24].try_into().unwrap()))
        .bitxor(u32::from_le_bytes(digest.packed_hash[24..28].try_into().unwrap()))
        .bitxor(u32::from_le_bytes(digest.packed_hash[28..32].try_into().unwrap()));
    self.weights_and_stores
        .binary_search_by_key(&key, |(weight, _)| *weight)
        .unwrap_or_else(|index| index - 1)
}

```
