### ISSUE TITLE
Question about CAS platform dimensions/corrupted CAS

### ISSUE THREAD

**Issue by kschzt** [TraceMachina/turbo-cache#299]
Hi! I wasn't sure where to post this question so I'm making an issue. We've been building exclusively with turbo-cache now for a few weeks and things mostly work great. We build a Chromium-based project with goma for Windows (cross on Linux workers) and Mac (on Mac workers), and sometimes attempt Mac cross builds on Linux (which works but has a non-RBE related issue). We build many very different versions based on the various upstream versions, several times a day. 

After a while, builds will suddenly fail with linker errors, solved by wiping the CAS and doing a clean build. I was wondering if in the RBE spec there are enough 'dimensions' for what we're doing, or if we're meant to be running two RBE clusters? 

Unfortunately there isn't a lot more debug info to go on at this point.

**Comment by allada** [comment]
It sounds like there is some kind of corruption somewhere. If this happens, try wrapping the CAS store in a `verify_store`. This will see if there was some kind of upload/download/disk corruption.

If it is possible, I'd love to get in there and check it out, but not sure how realistic this is on your side. Feel free to reach out to me in email (see github user) and we might be able to negotiate a way to help resolve this.

(To clearly answer the question, no there should be absolutely no need to run two clusters, the digest hash naturally partitions the data)

**Comment by kschzt** [comment]
@allada sounds good, let’s figure it out next week, I will drop you an email. Thanks!!
